### PR TITLE
Several values are unsigned this PR solve then to return correct value.

### PR DESCRIPTION
**Pull request by dmachadol**
Several values are unsigned this PR solve then to return correct value.

### CODE REVIEW

**Comment by sshoecraft** [comment]
merged - ty

**Comment by dmachadol** [comment]
Great!

**Comment by sshoecraft** [comment]
Did you want to take over this project?  I haven't worked on it a very long time.   I use the JBD agent in my solardirector project (along with sdconfig/cellmon/etc).

**Comment by dmachadol** [comment]
> Did you want to take over this project? I haven't worked on it a very long time. I use the JBD agent in my solardirector project (along with sdconfig/cellmon/etc).

ok!

**Comment by sshoecraft** [comment]
says dmachadol/jbdtool already exists ... ill do this later tonight

**Comment by dmachadol** [comment]
> says dmachadol/jbdtool already exists ... ill do this later tonight

deleted

**Comment by sshoecraft** [comment]
i did it but still shows as mine can you check if you see it?

**Pull request merged**
